# Site settings
title: "Айдар Галимов. Резюме"
description: "Experienced iOS Developer and Project Manager"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Айдар Галимов"
resume_title:                   "iOS Developer / Project Manager"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "aidar.gf@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+7(963)929-03-99"
resume_contact_address:         "Moscow, Russia"

resume_header_contact_info:     "Phone/Telegram/WhatsApp: +7(963)929-03-99 • Email: aidar.gf@gmail.com • Moscow, Russia"
display_header_contact_info:    "true"

resume_header_intro: "<p>Меня зовут Айдар, мне 21. На протяжении последних нескольких лет я занимаюсь разработкой iOS-приложений. Последний год руковожу командами мобильной разработки. За менее чем 3 года я полностью реализовал 4 приложения и создал свой стартап REVENT. Люблю осваивать новые технологии.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide

resume_section_experience:      true
resume_section_projects:        true
resume_section_education:       true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/aidar/"
  resume_facebook_url:          "https://www.facebook.com/galimovrussia"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  #resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
